### ISSUE TITLE
[Call for Contributors] TODO list

### ISSUE THREAD

**Issue by Liyulingyue** [Liyulingyue/ModulelyTools#1]
大家好，很高兴看到有一些朋友愿意维护这个项目，为了方便交流和开发，整理了一些TODO list。

- [x] 重构当前的代码结构。当前的代码结构是面向gradio的demo，实际上这个项目在开发过程中仅仅需要专注于维护接口逻辑，而不需要被gradio影响。因此，新的代码结构需要具有良好的分层，并且使得多个功能模块相互独立，方便后续开发，并且删除gradio页面。
  - [x] 将gradio相关信息删除或者移动到一个文件夹
  - [x] 将所有的llm相关的函数移动到同一个文件夹下
  - [x] 将所有解析相关的函数移动到同一个文件夹下
  - [x] 将ipynb转架构设计/py代码的函数移动到同一个文件夹下
  - [x] 将py代码转说明文档的函数移动到同一个文件夹下

- [ ] 优化实现路径
  - [ ] ipnyb解析及代码结构化_模块：
    - [ ]  ipnyb信息提取：Code属性/Code结合markdown属性，双路测试
    - [ ] 最终返回json元素结构的维度设计
    - [ ] 用户Query诉求与重构推理如何结合
    - [ ] 任务COT设计,链路中各环节Prompt设计
    - [ ] 最终结果抽取json，一键转换.py文件功能打通
    - [ ] 评测集确认对齐，确认评估维度指标
    - [ ] 实现上述结果后，考虑Token窗口限制
